### ISSUE TITLE
[Note] StateObject vs ObservedObject

### ISSUE THREAD

**Issue by cozytk** [DeveloperAcademy-POSTECH/CultureCenter-AppleMusicClone-CozyKyuRookie#12]
```swift
//
//  ArtistRow.swift
//  AppleMusicClone
//
//  Created by Hankyu Lee on 2022/07/07.
//

import SwiftUI

struct ArtistRow: View {
    
    @StateObject var searchVM: SearchViewModel
    
    var body: some View {
        
        LazyVStack {
            ForEach(searchVM.artists.indices, id: \.self) { index in
                HStack {
                    AsyncImage(url:
                                searchVM.artists[index].imageUrl) { image in
                        image
                            .resizable()
                            .aspectRatio(contentMode: .fit)
                            
                    } placeholder: {
                        RoundedRectangle(cornerRadius: 5)
                    }
                    .frame(width: 50, height: 50)
                    Text(searchVM.artists[index].inform)
                    Spacer()
                }
            }
        }
        
    }
}
```

<img width="720" alt="image" src="https://user-images.githubusercontent.com/59143479/177985691-50fa98b2-648c-485d-95c9-b2c642a7ac27.png">

https://jaesung0o0.medium.com/swiftui-data-flow-stateobject-vs-observedobject-e32a37d80dd2

#11 
`@StateObject` 인 searchVM이 상위뷰에서 값을 가져오기 때문에 `@ObservedObject` 로 사용하는게 맞는것 같아요!
저도 StateObject와 ObservedObject  두 프로퍼티로 선언했을 때의 각각 차이점에 대해서 제대로 이해했다기 보다는 "상위 뷰에서 하위뷰로 받을떄는 @Stateobjcet` 보다 `@ObservedObject`가 좋다 정도의 이해만 있어서 다른분들의 의견도 궁금하여 이슈로 만들어봅니다

@kyustudyo @Rookie0031

**Comment by Rookie0031** [comment]
오오 좋은 글 감사합니다 !! 

 제 생각을 말씀드리자면.. StateObject를 사용하는게 더 좋을 것 같습니다. 근데 지금 stateobject 프로퍼티 래퍼는 붙였지만 인스턴스화를 안한 상태라서 @StateObject var searchVM = SearchViewModel() 이렇게 써줘야할 것 같습니다.

 ObservedObject를 사용할시, 검색결과가 초기화 되는 단점이 있을 것 같습니다. 상위 뷰의 상태가 바껴서 상위 뷰가 다시 렌더링 된다면 하위뷰의 observedobject 를 사용하는 뷰도 다시 렌더링 되는데 인스턴스화하지않았기 때문에 검색결과가 초기화 될 것 같습니다.

아주 좋은 포인트며 중요한 문제네요!

**Comment by kyustudyo** [comment]
두분다 감사합니다..! 다시 생각하게 되었습니다.
제 생각을 말씀드리자면 observedObject를 쓰는게 날 것 같습니다. 
SearchView에서 viewmodel을 init 하고 하위뷰에서 init하지 않기때문에 observedObject 쓰는 것이 나을 것같습니다.

**Comment by cozytk** [comment]
@Rookie0031 

>제 생각을 말씀드리자면.. StateObject를 사용하는게 더 좋을 것 같습니다. 근데 지금 stateobject 프로퍼티 래퍼는 붙였지만 인스턴스화를 안한 >상태라서 https://github.com/StateObject var searchVM = SearchViewModel() 이렇게 써줘야할 것 같습니다.

이렇게하면 각 뷰에서 독립적인 searchVM이 생기는 것 아닌가여???

>ObservedObject를 사용할시, 검색결과가 초기화 되는 단점이 있을 것 같습니다. 상위 뷰의 상태가 바껴서 상위 뷰가 다시 렌더링 된다면 하위뷰>의 observedobject 를 사용하는 뷰도 다시 렌더링 되는데 인스턴스화하지않았기 때문에 검색결과가 초기화 될 것 같습니다.

상위뷰가 다시 렌더링되기는 하지만 `@StateObject` 로 선언된 변수는 뷰의 생명주기와 상관없이 다시 만들어지지 않기 때문에 현재처럼 상위뷰에서 값을 바인딩해서 가져오는 형태에서는 검색결과가 초기화되지 않을거라고 생각합니다!!

논의 덕에 `@StateObject`, `@ObservedObject` 에 대한 이해가 부족했고 SwiftUI에서는 source of truth이 변경되면 View가 copy 된다는 것을 다시 공부할 수 있었네요!!

개인적으로 더 공부 & 실험해보고 정리가 되면 공유해보도록 하겠습니다!!

**Comment by cozytk** [comment]
https://vapor3965.tistory.com/9

WWDC 2020 Data Essential 정리한 글인데 이 글도 배울점이 많아보입니다 👍
