### ISSUE TITLE
[Help] UIkit에서 view 상태 관리 하는법을 모르겠어요(@State 역할을 UIkit에서는 어떻게 구현하죠?) 

### ISSUE THREAD

**Issue by Rookie0031** [DeveloperAcademy-POSTECH/CultureCenter-AppleMusicClone-CozyKyuRookie#5]
## Related Task
None

## Problem
UIButton으로 버튼을 만들고, 버튼 탭 여부에 따라 버튼의 배경색깔을 달라지게 하고 싶음. 하지만 view를 다시 렌더링하지 않음

## Screenshot

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/103009135/177143194-cccef964-afa5-4363-bbea-c0427ae84343.png">

문제영상
https://user-images.githubusercontent.com/103009135/177143082-8d5c90c2-5d6d-4fd1-906d-767b3bbc3d54.mov

## Description
버튼을 눌렀을 때, 버튼 배경색이 파란색에서 빨간색으로 바뀌게 하고 싶습니다. 뭘 추가하면 될까요??

**Comment by kyustudyo** [comment]
여러가지 방법이 있는 것 같습니다. 그 중 하나는 다음과 같습니다.

```Swift
@objc internal func buttonTapAction(_ sender: UIButton) {
        sender.isSelected.toggle()
        if sender.isSelected {
            testButotn.backgroundColor = .red
        } else {
            testButotn.backgroundColor = .gray
        }
    }
```

**Comment by Rookie0031** [comment]
> 여러가지 방법이 있는 것 같습니다. 그 중 하나는 다음과 같습니다.
> 
> ```swift
> @objc internal func buttonTapAction(_ sender: UIButton) {
>         sender.isSelected.toggle()
>         if sender.isSelected {
>             testButotn.backgroundColor = .red
>         } else {
>             testButotn.backgroundColor = .gray
>         }
>     }
> ```

감사합니다! 혹시 전체 코드를 올려주실 수 있나요? testButton 을 어디서 선언햇는지 궁금하네요 제 코드에서 저렇게 변형하면 obj func 내에서 testbutton이 인식이 안되는 것 같아요!

**Comment by kyustudyo** [comment]
@Rookie0031 
``` swift
import UIKit

class ViewController: UIViewController {

    let testButotn: UIButton = {
        let button = UIButton()
        button.backgroundColor = .yellow
        return button
    }()

    override func viewDidLoad() {
        super.viewDidLoad()
        testButotn.addTarget(self, action: #selector(buttonTapAction(_:)), for: .touchDown)
        view.addSubview(testButotn)
        testButotn.translatesAutoresizingMaskIntoConstraints = false
        testButotn.bottomAnchor.constraint(equalTo: self.view.bottomAnchor, constant: -80).isActive = true
        testButotn.leadingAnchor.constraint(equalTo: self.view.leadingAnchor, constant: 80).isActive = true
        testButotn.trailingAnchor.constraint(equalTo: self.view.trailingAnchor, constant: -80).isActive = true

    }

    @objc internal func buttonTapAction(_ sender: UIButton) {
            sender.isSelected.toggle()
            if sender.isSelected {
                testButotn.backgroundColor = .red
            } else {
                testButotn.backgroundColor = .gray
            }
        }
}

**Comment by Rookie0031** [comment]
감사합니다 규 짱짱
