### ISSUE TITLE
[Help] feat/2-tabViewUI 브렌치 빌드 실패

### ISSUE THREAD

**Issue by cozytk** [DeveloperAcademy-POSTECH/CultureCenter-AppleMusicClone-CozyKyuRookie#9]
## Related Task
\#4

## Problem
Build 실패

## Screenshot
<img width="631" alt="image" src="https://user-images.githubusercontent.com/59143479/177701234-51b341a4-f8b8-4389-9103-c118d9786b34.png">

## Description
규 브렌치에 checkout 하고 빌드해도 안되네요

**Comment by cozytk** [comment]
@Rookie0031 @kyustudyo

**Comment by cozytk** [comment]
<img width="631" alt="image" src="https://user-images.githubusercontent.com/59143479/177701701-48583110-8680-4c7d-8c0b-2c8b93bbf73d.png">

MainViews는 파일이 안보이는데 혹시 왜이러는지 아시나요유

**Comment by cozytk** [comment]
일단 임의로 https://raw.githubusercontent.com/DeveloperAcademy-POSTECH/CultureCenter-AppleMusicClone-CozyKyuRookie/f784f0fe550811d615e35450f82e068b06ac8682/AppleMusicClone/Views/MainView.swift 여기서 파일 복붙해서 생성한다음에 빌드 성공했ㅎ습니다!!!! 왜그랬는지 아시는분~

**Comment by cozytk** [comment]
그리고 이렇게 맘대로 새로 생성해도되나여?! pbxproj 막 꼬이고 안이럴까 하는 걱정이~~~

**Comment by Rookie0031** [comment]
> <img alt="image" width="631" src="https://user-images.githubusercontent.com/59143479/177701701-48583110-8680-4c7d-8c0b-2c8b93bbf73d.png">
> 
> MainViews는 파일이 안보이는데 혹시 왜이러는지 아시나요유

이거 저도 모르겟지만 머지과정에서 없어졋습니다. 근데 그 폴더에 MainView 파일이 있긴해서 add file해서 넣으시면 해결됩니다!
